#! /usr/bin/env python
from joblib import FJob

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()

    
    parser.add_argument(
    '-m', '--server', dest='server', 
    nargs='?', default='smtp.gmail.com', 
    help='Smtp server.')

    parser.add_argument('-p', '--port', dest='port', 
    nargs='?', default=587, help='Smtp server.')

    parser.add_argument('-u', '--user', dest='user', 
    nargs='?', help='Mail username')

    parser.add_argument('-w', '--password', dest='password', 
    nargs='?', help='Your password.')

    parser.add_argument('-r', '--resume', dest='resume', 
    nargs='?', help='Your resume.')

    parser.add_argument('-f', '--file-template', 
    dest='template', default= 'Some msg to send.', 
    nargs='?', help='Some message.')

    args = parser.parse_args()
    
    find = FJob(args.server, args.port, 
    args.user, args.password, args.resume, args.template)






